spring:
  datasource:
    url: jdbc:sqlite:${user.home}/Desktop/tasks.db
    username: sa
    password: sa
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update